### ISSUE TITLE
Hello, I update the latest version，it does not normal to run!

### ISSUE THREAD

**Issue by Joy1024** [ittus/vue-monthly-picker#10]
![vue-monthly-error](https://user-images.githubusercontent.com/3068746/40363006-c7717f54-5e00-11e8-83d2-d9267b25ec33.png)

**Comment by ittus** [comment]
Do you pass a value of moment object to component?

**Comment by Joy1024** [comment]
Yes, I use moment!

My code is: 
<vue-monthly-picker id="monthly-picker" v-model="params.monthly" @selected="$set(params, 'month', $event.format('YYYY/MM') ); search()" ></vue-monthly-picker>

<script>
    window.onPageMounted = function(vm){
        let monthly = new moment();
        let month = monthly.format('YYYY/MM')
        vm.$set(vm.params, 'month', month)
        vm.$set(vm.params, 'monthly', monthly)
    }
</script>

**Comment by ittus** [comment]
It seems ok https://codesandbox.io/s/6wryw5n1l3

**Comment by ittus** [comment]
It's nice idea. I will implement it 👍

**Comment by ittus** [comment]
Release in https://github.com/ittus/vue-monthly-picker/releases/tag/v0.2.2

**Comment by Joy1024** [comment]
thank you much!
