### ISSUE TITLE
it seems that the monthly picker is invisible in code

### ISSUE THREAD

**Issue by JakeAtTurner** [ittus/vue-monthly-picker#13]
The Component is not showing up in my application.

**Comment by JakeAtTurner** [comment]
The code is displaying but the component is not there, I think it might be a issue with CSS.

<div class="vue-monthly-picker"><div class="month-picker-wrapper"><div type="text" autocomplete="off" tabindex="0" class="month-year-label picker"><div class="month-year-display placeholder">
          
        </div></div> <div class="text"></div> <div tabindex="-1" class="date-popover hidden" style="display: none;"><div class="picker" style="text-align: center;"><div class="flexbox"><span class="prev"></span> <div>2018</div> <span class="next"></span></div> <div class="flexbox monthItem"><div class="item active">1
            </div><div class="item active">2
            </div><div class="item active">3
            </div><div class="item active">4
            </div><div class="item active">5
            </div><div class="item active">6
            </div><div class="item active">7
            </div><div class="item active">8
            </div><div class="item active">9
            </div><div class="item active">10
            </div><div class="item active">11
            </div><div class="item active">12
            </div></div></div></div></div></div>

**Comment by ittus** [comment]
@JakeAtTurner Can you show how do you include `<vue-monthly-picker />` in your code?

**Comment by ittus** [comment]
@Awaishkumar Did you import component?

`import VueMonthlyPicker  from 'vue-monthly-picker`?

**Comment by Awaishkumar** [comment]
import VueMonthlyPicker from 'vue-monthly-picker'
Vue.component('my-component', {
    components: {
        VueMonthlyPicker
    }
});



and than used like this 
<vue-monthly-picker
 v-model="selectedMonth">
</vue-monthly-picker>



@ittus Does it depend on any react or npm versions?

**Comment by ibajerai** [comment]
omg this is not how you use it

`<vue-monthly-picker
 v-model="selectedMonth">
</vue-monthly-picker>`

If you look at the source for the demo `node_modules/vue-monthly-picker/src/app.vue` you will see it declared like this 
`
      <vue-monthly-picker
       :inputClass="{'input': isDisplayInput}"
       :disabled="isDisable"
       :monthLabels="locale"
       :min="min"
       :max="max"
       @selected="handleSelect"
       v-model="selectedMonth">
      </vue-monthly-picker>
`

Where `selectedMonth` is a moment object.

If you don't bind a value to the component it sets it to "placeholder" mode, not displaying in the page.

How hard is that to put in the install steps?

**Comment by ibajerai** [comment]
@Awaishkumar this is a vue component not react, it is dependant on the vue.js library.

https://vuejs.org/

**Comment by ittus** [comment]
@JakeAtTurner @ibajerai 
You need to passed inputClass="input" to make component display as an input, otherwise it will displayed as a div by default.

I've changed the behavior, now it will displayed as an input by default https://github.com/ittus/vue-monthly-picker/commit/afd308f30034d50f9209eb856f4b4f44747406f3
