### ISSUE TITLE
Can't choose max value

### ISSUE THREAD

**Issue by tuanpm996** [ittus/vue-monthly-picker#20]
Can't pick max value despite can choose min value

**Comment by ittus** [comment]
Hi @tuanpm996 

I checked on https://ittus.github.io/vue-monthly-picker/#/ and see we can still set the max value

You can see the disabled months in below image

![screen shot 2019-02-21 at 17 57 12](https://user-images.githubusercontent.com/5120965/53156287-668f1b80-3602-11e9-9e48-22bb19fd18ba.png)
