### ISSUE TITLE
Can't set min value

### ISSUE THREAD

**Issue by dashqa** [ittus/vue-monthly-picker#21]
There is an error `Error in render: "TypeError: this.min.isBefore is not a function"` when I set min value, however I can set max value and it works.

**Comment by iamshengsheng** [comment]
> There is an error `Error in render: "TypeError: this.min.isBefore is not a function"` when I set min value, however I can set max value and it works.

Seems like you are passing a string value when you need to pass a moment value. You just need to import moment and pass the value in min like this **min: moment("2010-10-21")**.  We also encountered this error, and this is our solution. Hope this helps you too.

`<template>
  <div>
    <vue-monthly-picker
      :min="minDate"
      v-model="monthSelected">
    </vue-monthly-picker>
  </div>
</template>

<script>
  import VueMonthlyPicker from 'vue-monthly-picker'
  import moment from 'moment'
  
  export default {
    components: {
      VueMonthlyPicker,
    },
    data() {
      return {
        monthSelected: "",
        minDate: moment("2010-10-21") 
      }
    }
  }
</script>`

**Comment by dashqa** [comment]
@iamshengsheng 
yeah, thanks a lot!
