### ISSUE TITLE
Translate Display format

### ISSUE THREAD

**Issue by cesarureno** [ittus/vue-monthly-picker#22]
Hello, is there any possibility to translate dateFormat option?

**Comment by ittus** [comment]
You can pass `dateFormat` to component, for example 
`dateFormat="YYYY/MM"` or `dateFormat="YYYY年MM月"`

**Comment by cesarureno** [comment]
I'm using dateFormat = "MMM-YYYY" and the result is next

<img width="303" alt="Screen Shot 2019-04-12 at 00 47 52" src="https://user-images.githubusercontent.com/1313729/56014904-bdd57200-5cbc-11e9-9a9a-d6831db58587.png">

But the month is showed in English and I need translate it to Spanish
