### ISSUE TITLE
format

### ISSUE THREAD

**Issue by padmaseenivasan** [ittus/vue-monthly-picker#3]
Can we change input format like 2017 - Feb

**Comment by ittus** [comment]
Thank you very much.
`dateFormat` is supported in `v0.1.6` 
https://github.com/ittus/vue-monthly-picker/releases/tag/v0.1.6

You can pass `dateFormat="YYYY - MMM"` to get `2017 - Feb`

**Comment by padmaseenivasan** [comment]
Thank you!!!!! Ittus...
