### ISSUE TITLE
It's not working. 

### ISSUE THREAD

**Issue by ifarooq** [ittus/vue-monthly-picker#6]
i can see the elements on inspect element but its not displaying anything. There is no error in console as well.

**Comment by ifarooq** [comment]
Never mind it's sorted out. Basically the place-holder prop is required, if it's not passed nothing shows up. 
 <vue-monthly-picker @selected="setYearMonth"  place-holder="Select Year and Month" :month-labels="monthLabels"
 v-model="year_month">
</vue-monthly-picker>

**Comment by ittus** [comment]
@ifarooq Thank you for your contribution. I'll update the document.

**Comment by ifarooq** [comment]
You are welcome, in next update if you can add a feature to pass a default value, that would be great, this is needed when we use it in update form.  I have done this using jQuery. 
  $('#to-year-month .month-year-display').html(data.to_year+'/'+data.to_month);
Like <vue-monthly-picker  :default="2017/12" ....
