### ISSUE TITLE
Null Value

### ISSUE THREAD

**Issue by pietrorobbi** [ittus/vue-monthly-picker#9]
Hi,
I need to initialize the component with an empty value, so I pass the NULL value, but in this way the component does not seem to work: the click does not open the calendar. 
There are no errors in the console.

Here the model property binded
```
 StartDate: {
      get: function () {
        let date = null

        if (this.StartDate) {
          date = moment(this.StartDate)
        }

        return (date && date.isValid() ? date : null)
      },
      set: function (val) {
        this.StartDate= val.format('YYYY-MM-DD')
      }
    },
```

**Comment by ittus** [comment]
Can you check again value of `StartDate`? I still can see the picker if I pass `null` to component
https://codesandbox.io/s/8y5yzv00nj

**Comment by pietrorobbi** [comment]
Ok, now my code work! 
I've find a condition that disable the component when value is null!

Sorry for mistake
